### PR TITLE
Bump angular dependency to ~1.3.0.

### PR DESCRIPTION
**Pull request by limonte**

### CODE REVIEW

**Comment by sambs** [comment]
Hi @limonte, I've updated the angular dependency to be <2.0.0. Seemed more flexible than bumping to ~1.3.0.

**Comment by limonte** [comment]
@sambs Great! Can you please make release on GH, so I can bump angular-sb-debounce to 0.3.0 (I'm using bower)

**Comment by sambs** [comment]
@limonte oops, sorry - I've pushed a 0.3.0 tag now.

**Comment by limonte** [comment]
@sambs Thank you!

**Pull request closed without merging**
